In [62]:
import math
def get_index(item, lst):
    enumerated = list(enumerate(lst))
    def get_index_step(item, enumerated):
        if len(enumerated) == 1:
            return enumerated[0][0]
        middle_index = math.floor(len(enumerated)/2)
        if enumerated[middle_index][1] > item:
            get_index_step(item, enumerated[:middle_index])
        elif enumerated[middle_index][1] == item:
            return(True #(enumerated[middle_index]))
        else:
            get_index_step(item, enumerated[middle_index:])
    print(get_index_step(item, enumerated))
    return get_index_step(item, enumerated)
    
        

In [63]:
print(get_index(8,[2,3,4, 8,12]))

None
None


In [32]:
list(enumerate([2,3,4, 8,12]))

[(0, 2), (1, 3), (2, 4), (3, 8), (4, 12)]

In [73]:
def merge_sort(A, B):
    merged = []
    while len(A)>0:
        a = A.pop(0)
        while len(B)>0:
            b = B.pop(0)
            if b <= a:
                merged.append(b)
            else:
                merged.append(a)
                break
    
    return merged

In [74]:
merge_sort([3,5,7], [1,8])


[1, 3]

In [77]:
import sklearn.datasets

In [80]:
iris_data = sklearn.datasets.load_iris()

In [106]:
import sklearn.linear_model
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [111]:
X_train, X_test, y_train, y_test = train_test_split(iris_data['data'], iris_data['target'], test_size=0.5, random_state=0)

In [112]:
log_model = sklearn.linear_model.LogisticRegression()
log_model.fit(X_train, y_train)

/home/adam/.local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/adam/.local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [113]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [126]:
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix

In [125]:
for target in range(3): 
    idx = y_test == target
    log_predicted = log_model.predict(X_test)
    nb_predicted = nb_model.predict(X_test)
    log_accuracy = sum(log_predicted[idx] == y_test[idx])/len(log_predicted[idx])
    nb_accuracy =  sum(nb_predicted[idx] == y_test[idx])/len(nb_predicted[idx])
    print(log_accuracy, nb_accuracy)

predicted_log = log_model.predict(X_test) 
print(classification_report(y_test, predicted_log))
predicted_nb = nb_model.predict(X_test)
print(classification_report(y_test, predicted_nb ))

1.0 1.0
0.6 1.0
1.0 0.8333333333333334
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      0.60      0.75        30
           2       0.67      1.00      0.80        24

    accuracy                           0.84        75
   macro avg       0.89      0.87      0.85        75
weighted avg       0.89      0.84      0.84        75

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.88      1.00      0.94        30
           2       1.00      0.83      0.91        24

    accuracy                           0.95        75
   macro avg       0.96      0.94      0.95        75
weighted avg       0.95      0.95      0.95        75



In [131]:
import numpy as np
nb_cm = confusion_matrix(nb_model.predict(X_test), y_test)
nb_cm = nb_cm / nb_cm.sum(axis=1)[:, np.newaxis]
nb_cm

array([[1.        , 0.        , 0.        ],
       [0.        , 0.88235294, 0.11764706],
       [0.        , 0.        , 1.        ]])

In [132]:
log_cm = confusion_matrix(log_model.predict(X_test), y_test)
log_cm = log_cm / log_cm.sum(axis=1)[:, np.newaxis]
log_cm

array([[1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.33333333, 0.66666667]])

In [135]:
nb_cm

array([[1.        , 0.        , 0.        ],
       [0.        , 0.88235294, 0.11764706],
       [0.        , 0.        , 1.        ]])

In [136]:
log_cm = confusion_matrix(log_model.predict(X_test), y_test)
log_cm

array([[21,  0,  0],
       [ 0, 18,  0],
       [ 0, 12, 24]])

In [141]:
log_cm.sum(axis=1)[:,np.newaxis]

array([[21],
       [18],
       [36]])